services:
  skillshare:
    image: mariadb
    container_name: skillsharedb
    restart: unless-stopped
    ports:
      - '3383:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - skillshare_db:/var/lib/mysql
      - ../database:/docker-entrypoint-initdb.d
    networks:
      - skillshare_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: skillshare_phpmyadmin
    restart: unless-stopped
    ports:
      - '8083:80'
    environment:
      - PMA_HOST=skillshare
      - PMA_PORT=${PMA_PORT}
    depends_on:
      - skillshare
    networks:
      - skillshare_network

  mailpit:
    image: axllent/mailpit
    container_name: skillshare_mail
    restart: unless-stopped
    ports:
      - ${MAILPIT_HTTP_PORT}:8025
      - ${MAILPIT_SMTP_PORT}:1025
    networks:
      - skillshare_network

volumes:
  skillshare_db:

networks:
  skillshare_network:
    external: true
    name: skillshare_network
